MOTECH-2907: Add visit UUID to create encounter task action
motech/modules pull request #420
Opened 2016-09-09 17:00 UTC by palbecki

2016-09-09 17:00 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-09 17:00 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-09 17:00 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-09 17:00 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-09 17:12 UTC, pgesek commented
test this please

2016-09-12 11:22 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Encounter.java
>      public Encounter(Location location, EncounterType encounterType, Date encounterDatetime, Patient patient,
Please add additional constructor to have backward compatibility

2016-09-12 11:22 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Encounter.java
> +    @Override
why do you move hashCode method below equals ?

2016-09-12 11:22 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Visit.java
> +    public Visit() {
do we need default constructor ?

2016-09-12 11:23 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSVisitServiceImpl.java
> +            return null;
Log error here, similar to other services

2016-09-12 11:23 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/OpenMRSActionProxyService.java
> +    Encounter createEncounter(String configName, DateTime encounterDatetime, String encounterType,
adjust javadoc

2016-09-12 11:25 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +        Visit visit = visitService.getVisitByUuid(configName, visitUuid);
visitUuid is optional field so you should handle potential null

2016-09-12 11:25 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/it/MRSTasksIntegrationBundleIT.java
> +                createdPatient, null, Collections.singletonList(createdProvider.getPerson()), null);
include creating visit in ITs

2016-09-12 11:25 UTC, palbecki commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Visit.java
> +    public Visit() {
I use it in unit tests.

2016-09-12 11:26 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        openMRSActionProxyService.createEncounter(CONFIG_NAME, new DateTime(encounter.getEncounterDatetime()),
do not change this test, it should still check if proper encounter is returned from createEncounter service

2016-09-15 08:49 UTC, palbecki commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Encounter.java
>      public Encounter(Location location, EncounterType encounterType, Date encounterDatetime, Patient patient,
done

2016-09-15 08:51 UTC, palbecki commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/OpenMRSActionProxyService.java
> +    Encounter createEncounter(String configName, DateTime encounterDatetime, String encounterType,
done.

2016-09-15 08:51 UTC, palbecki reviewed
fix

2016-09-15 13:30 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        verify(encounterService).createEncounter(eq(CONFIG_NAME), encounterCaptor.capture());
this is redundant

2016-09-15 13:30 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        assertEquals(encounter, encounterCaptor.getValue());
this is redundant

2016-09-15 13:32 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/helper/EventHelper.java
> +
remove additional line

2016-09-15 13:32 UTC, kmadej requested changes

2016-09-16 09:18 UTC, kmadej approved these changes

2016-09-16 09:19 UTC, merged