MOTECH-2926: Don't Send Observation If Observation Value is Null or…
motech/modules pull request #425
Opened 2016-09-14 12:44 UTC by palbecki

…Empty String

2016-09-14 12:44 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-14 12:44 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-14 12:44 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-15 11:24 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +                if (observation.getValue() != null && StringUtils.isNotEmpty(observation.getValue().getDisplay())) {
please move this condition to separate method. It will be more readable what you are doing and why

2016-09-15 11:25 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +            if (StringUtils.isNotEmpty(observations.get(observationConceptName))) {
the same as above

2016-09-15 11:27 UTC, kmadej requested changes

2016-09-15 13:15 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +                if (observationValueIsNotEmpty(observation)) {
additionally, please log info if value is empty, that we omit creating this observation because of empty value. I think WARN level will be ok

2016-09-15 13:16 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +            if (valueIsNotEmpty(observations, observationConceptName)) {
additionally, please log info if value is empty, that we omit creating this observation because of empty value. I think WARN level will be ok

2016-09-15 13:17 UTC, kmadej requested changes

2016-09-16 08:50 UTC, kmadej approved these changes

2016-09-16 08:50 UTC, merged