MOTECH-2939: Allowed Sending Multiple Observations of the Same Type
motech/modules pull request #434
Opened 2016-09-19 14:33 UTC by MichalKus

Now it is possible to add multiple values to the same type of Observation. Each value should be separate by comma.

2016-09-19 14:33 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-19 14:33 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-19 14:34 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-20 12:36 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +                String[] observationsValues = observations.get(observationConceptName).replace(" ", "").split(",");
what if value string has space, we should not remove every space in string

2016-09-20 12:36 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +                String[] observationsValues = observations.get(observationConceptName).replace(" ", "").split(",");
change variable name to observationValues

2016-09-20 12:38 UTC, kmadej commented
Please adjust/add unit test

2016-09-20 12:39 UTC, kmadej requested changes
change

2016-09-20 14:20 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        List<Observation> obsList = createObservationListWithManyObservations();
I think it would be  better to use existing method createObservationList and add a parameter, how many observations should be added

2016-09-20 14:21 UTC, kmadej requested changes

2016-09-21 07:50 UTC, kmadej approved these changes

2016-09-21 08:26 UTC, merged