Motech 2885: Get most recent observation by patient and concept ID
motech/modules pull request #440
Opened 2016-09-21 13:27 UTC by mkruszynski

2016-09-23 12:29 UTC, pkornowski commented
@kmadej Looks good to me.

2016-09-23 14:57 UTC, kmadej commented
On JIRA in ticket description there is the following information 'This data source can return 0 or 1 result. The data source bubbles are at the bottom of the ticket. Note, we should also be able to filter if 0 results are returned using a task filter'. So please handle this properly

2016-09-28 08:25 UTC, kmadej commented
Please resolve conflicts, and if data source returns 0, there should be possibility to filter this value. Now you return null, so it is not possible

2016-09-30 09:50 UTC, kmadej commented
The feature I mentioned above has still not been implemented

2016-10-11 11:14 UTC, kmadej requested changes

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSObservationServiceImpl.java
> +            LOGGER.error("Error while fetching observations with Patient uuid: " + patientUUID + " and Concept uuid: " + conceptUUID);
throw exception with detailed error message

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/OpenMRSTaskDataProvider.java
> +                    latestObservation.setNumberOfObservations("1");
please move this few lines into new method

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/OpenMRSTaskDataProviderTest.java
>          when(configService.getConfigs()).thenReturn(new Configs());
please add unit test

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/resource/impl/ObservationResourceImplTest.java
> +        assertThat(requestCaptor.getValue().getBody(), nullValue());
please remove this assert, I know that other tests have this line, however this check doesnt have much sense

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/resource/impl/ObservationResourceImpl.java
> +        Map<Type, Object> adapter = new HashMap<>();
why do you change this method ?

2016-10-11 11:14 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Observation.java
> +            return observationValue;
I see that you are using this deserializer only in method not connected with this data provider. What's the reason ?

2016-10-11 12:09 UTC, mkruszynski commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Observation.java
> +            return observationValue;
When I was resolving conflicts after branch update I met conflicts in ObservationValue json Deserializer. I'll check that this change is necessary.

2016-10-11 13:40 UTC, mkruszynski commented on openmrs/src/main/java/org/motechproject/openmrs/domain/Observation.java
> +            return observationValue;
@kmadej I checked it and this function is used to get latest observation. Deserializer of ObservationValue is needed, because this value in response json can be a primitive or json object.

2016-10-11 14:44 UTC, kmadej approved these changes

2016-10-11 14:45 UTC, merged