MOTECH-2915: Failing task when create encounter gets 400 error
motech/modules pull request #447
Opened 2016-09-22 12:48 UTC by 0nat

2016-09-22 12:48 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-22 12:48 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-23 14:01 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +            throw new OpenMRSException("Could not create encounter with patient uuid: " + encounter.getPatient().getUuid(), e);
I am not sure if information we need will be displayed here. Can you verify this ? We should have here exact informaction what is wrong when 400 returned. I think getResponseBodyAsString should be used here.

2016-09-23 14:03 UTC, kmadej requested changes

2016-09-27 08:56 UTC, kmadej requested changes

2016-09-27 08:56 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +            throw new OpenMRSException("Could not create encounter with patient uuid: " + encounter.getPatient().getUuid() + " " + e.getMessage() + " " + e.getResponseBodyAsString(), e);
please use String.format. We should avoid concatting strings, because it creates and stores multiple strings in Java String pool

2016-09-28 08:15 UTC, kmadej approved these changes

2016-09-28 08:15 UTC, merged