MOTECH-2918 Added DHIS2 status response to DEBUG log and throwing DhisWebException when response is ERROR.
motech/modules pull request #449
Opened 2016-09-22 16:03 UTC by mjazdzdewski

2016-09-22 16:03 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-22 16:04 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-09-23 15:06 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/rest/service/impl/DhisWebServiceImpl.java
> +        if (status.getStatus() == DhisStatus.ERROR) {
Did you check it correctly ? In the ticket description on JIRA there is an information that response can return 200 (OK) but response body may contain 'ERROR', so it seems that you do not include this condition

2016-09-23 15:06 UTC, kmadej requested changes

2016-09-26 07:45 UTC, kmadej requested changes

2016-09-26 07:45 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/rest/service/impl/DhisWebServiceImpl.java
> +            String msg = String.format("Error in DHIS2 status response: %s", status.getStatus().toString());
we should log here more information if possible. Ideally the reason why there is a error. Additionally this 'status.getStatus().toString()' is redundant, because in this condition there will be always ERROR type

2016-09-27 09:49 UTC, kmadej requested changes

2016-09-27 09:49 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/rest/service/impl/DhisWebServiceImpl.java
> +                throw new DhisWebException(msg);
1. From JIRA 'Ideally task should fail properly with an error'. I see that task fails with exception and brief error message. We should extend this to fail properly with an error
2. Additionally as far as I understand, warn method from statusMessageService is logging this message. So now we are logging on debug level using LOGGER and then using service ? We should standardize this

2016-09-28 08:27 UTC, kmadej requested changes

2016-09-28 08:27 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/rest/service/impl/DhisWebServiceImpl.java
> +                statusMessageService.warn(msg, MODULE_NAME);
debug level

2016-09-28 08:56 UTC, kmadej requested changes

2016-09-28 08:56 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/rest/service/impl/DhisWebServiceImpl.java
> +                statusMessageService.warn(msg, MODULE_NAME);
I have read once again ticket description and I think that we should omit logging this, just throw exception and task will fail

2016-09-28 11:12 UTC, kmadej approved these changes

2016-09-28 11:13 UTC, merged