MOTECH-2717 Using XLMNS + APP_ID as an unique identifier, and changed tests accordingly
motech/modules pull request #459
Opened 2016-10-03 16:11 UTC by mjazdzdewski

…

2016-10-03 16:11 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-10-03 16:11 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-10-04 09:49 UTC, kmadej requested changes

2016-10-04 09:49 UTC, kmadej commented on commcare/src/test/java/org/motechproject/commcare/util/ResponseXML.java
> +                "      xmlns=\"" + DummyCommcareSchema.XMLNS1 + DummyCommcareSchema.APP_ID1 + "\">\n" +
app id should not be included in xmlns value

2016-10-17 12:34 UTC, kmadej requested changes

2016-10-17 12:34 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/FormTriggerBuilder.java
> +            return new TriggerEventRequest(displayName, FORMS_EVENT + "." + config.getName() + "." + form.getXmlns(),
first of all,  there should be one return statement. Secondly it should be better to verify if commcareAppId is null in one line

2016-10-17 12:34 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/FormActionBuilder.java
> +                    String appId = application.getCommcareAppId();
this should be done in one line

2016-10-17 12:34 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/FormActionBuilder.java
> +        parameters.add(builder.createActionParameterRequest());
move this logic into private method 'addXmlnsParameter'

2016-10-17 12:34 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/service/impl/CommcareFormsEventParser.java
> +            }
there should be one return statement, please also simplify this code. Additionally add warning that app_id is null

2016-10-17 14:11 UTC, kmadej approved these changes

2016-10-17 14:12 UTC, merged