MOTECH-2891: Created report task actions
motech/modules pull request #469
Opened 2016-10-21 11:52 UTC by mkruszynski

2016-10-21 14:50 UTC, kmadej requested changes

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/ReportActionBuilder.java
> +        for (ReportsMetadataInfo reportsMetadataInfo : schemaService.getReportsMetadata(config.getName())) {
method with objects connected with db (entity annotation) should be in transaction (please remember that transactional annotation only works for public methods, so in thi case add this to buildActions method

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/ReportActionBuilder.java
> +
remove empty line

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/ReportActionBuilder.java
> +
remove empty line

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/ReportActionBuilder.java
> +
remove empty line

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/events/ReportActionEventHandler.java
> +
remove empty line

2016-10-21 14:50 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/events/ReportActionEventHandler.java
> + */
adjust javadoc, it is report handler

2016-10-24 14:52 UTC, mkruszynski commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/ReportActionBuilder.java
> +        for (ReportsMetadataInfo reportsMetadataInfo : schemaService.getReportsMetadata(config.getName())) {
@kmadej I tested this. With Transactional annotation on this method sync isn't working. Moreover this function is already in transaction, because it is called by one of functions used in ConfigurationManager class, where all public methods have this annotation.

2016-10-26 07:36 UTC, merged