MOTECH-2959: Added unit tests for Create Order action.
motech/modules pull request #470
Opened 2016-10-21 12:11 UTC by pkornowski

There are unit tests for https://github.com/motech/modules/pull/468

2016-10-21 12:18 UTC, kmadej requested changes

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/resources/json/order/order-create.json
> +}
add patient, type is a name (for example 'order')

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        location.setName("testLocation");
remove setting location

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        visit.setUuid("40");
remove this

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        Concept concept = createTestConcept("testConcept");
use uuid

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        Order order = new Order("testType", encounter, provider, patient, concept, Order.CareSetting.INPATIENT);
instead of "testType" use "order"

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        assertEquals(order, orderCaptor.getValue());
verify if this action return object

2016-10-21 12:18 UTC, kmadej commented on openmrs/src/test/resources/json/order/order-create.json
> +  "type": "p123456-2821-4334-ab85-eef3cd8fea8c",
why this is uuid ? how this test works ?

2016-10-21 13:31 UTC, kmadej commented on openmrs/src/test/resources/json/order/order-prepare.json
> +  }
the json which is sending to OpenMRS server looks differently :
{
"patient" : "uuid",
"concept" : "uuid",
....
}

2016-10-25 06:21 UTC, pkornowski commented
I closed this PR. It will be continued here https://github.com/motech/modules/pull/473

2016-10-25 06:21 UTC, closed without merging