MOTECH-3015 Added app_id URL parameter handling to FullFormController
motech/modules pull request #472
Opened 2016-10-24 08:21 UTC by mjazdzdewski

2016-10-24 08:21 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-10-24 08:21 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-10-27 10:13 UTC, kmadej requested changes

2016-10-27 10:13 UTC, kmadej commented on commcare/src/test/java/org/motechproject/commcare/web/FullFormControllerTest.java
> +        assertEquals(2, attributes.size());
please adjust this test, add app_id value and check if attributes map has this value

2016-10-27 10:13 UTC, kmadej commented on commcare/src/test/java/org/motechproject/commcare/web/FullFormControllerTest.java
> +        assertEquals(5, attributes.size());
the same as above

2016-10-27 11:57 UTC, kmadej approved these changes

2016-10-27 11:57 UTC, merged