MOTECH-2973 Import Forms By Form ID
motech/modules pull request #481
Opened 2016-11-21 03:03 UTC by srujan92

1. Created a dropdown option, input field for "By Form Id" and added related js functions.
2. Added function in controller and created new methods for form import through id.
3. New test cases are added for the newly added methods.

2016-11-21 03:03 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-11-21 03:03 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-11-22 14:09 UTC, kmadej requested changes
The feature seems to work correctly, please adjust code with my feedback

2016-11-22 14:09 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/pull/CommcareFormImporter.java
> +     * API will be made underneath, and the returned total count will be returned by this method.
this method does not return total count

2016-11-22 14:09 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/pull/CommcareFormImporter.java
> +     * @throws NullPointerException if the form id is null or invalid
this method never throw NPE because you are catching this exception

2016-11-22 14:09 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/pull/CommcareFormImporterImpl.java
> +        } catch (NullPointerException e) {
catching NPE is always bad idea, you should rather modificate retrieveForm method from formService to return null if form does not exist and then "return form != null'

2016-11-23 08:39 UTC, kmadej approved these changes

2016-11-23 08:39 UTC, merged