MOTECH-3059 Encounter type will be represented by uuid instead of name
motech/modules pull request #496
Opened 2016-11-29 13:05 UTC by shanmukhm

2016-11-29 14:40 UTC, kmadej commented
It looks good to me, @shanmukhm did you check OpenMRS ITs after your changes ?

2016-11-29 14:49 UTC, shanmukhm commented
@kmadej I ran ITs. I'm getting '400 Bad Request' error (at OpenMRSPatientServiceImpl.createPatient()).
I am getting the same error even if I run ITs on master branch. I think this error is related to configuration and not related to what I changed. Anyway, can you ask someone to run ITs if possible?

2016-11-29 14:50 UTC, kmadej commented
Ok no problem, @pkornowski please run ITs with this changes locally

2016-11-29 15:34 UTC, pkornowski commented
@shanmukhm @kmadej 
I run ITs locally with this changes and I have 400 as well, but at the first place null pointer appeared in the `MRSTasksIntegrationBundleIT.setUp:157->createEncounterTestData:381->prepareEncounterType:549 NullPointer`.

There is stack trace:

`Tests run: 54, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 1,087.932 sec <<< FAILURE! - in org.motechproject.openmrs.it.version1_12.MRSIntegrationTests
testOpenMRSPatientDataSourceAndCreatePatientAction(org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT)  Time elapsed: 121.07 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.prepareEncounterType(MRSTasksIntegrationBundleIT.java:549)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.createEncounterTestData(MRSTasksIntegrationBundleIT.java:381)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.setUp(MRSTasksIntegrationBundleIT.java:157)

testOpenMRSEncounterDataSourceAndCreateEncounterAction(org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT)  Time elapsed: 120.372 sec  <<< ERROR!
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:495)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:446)
	at org.motechproject.openmrs.resource.impl.BaseResource.exchange(BaseResource.java:103)
	at org.motechproject.openmrs.resource.impl.BaseResource.postForJson(BaseResource.java:62)
	at org.motechproject.openmrs.resource.impl.PatientResourceImpl.createPatient(PatientResourceImpl.java:44)
	at org.motechproject.openmrs.service.impl.OpenMRSPatientServiceImpl.createPatient(OpenMRSPatientServiceImpl.java:86)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.createPatientTestData(MRSTasksIntegrationBundleIT.java:376)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.setUp(MRSTasksIntegrationBundleIT.java:156)

testOpenMRSProviderDataSourceAndCreateEncounterAction(org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT)  Time elapsed: 120.53 sec  <<< ERROR!
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:495)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:446)
	at org.motechproject.openmrs.resource.impl.BaseResource.exchange(BaseResource.java:103)
	at org.motechproject.openmrs.resource.impl.BaseResource.postForJson(BaseResource.java:62)
	at org.motechproject.openmrs.resource.impl.PatientResourceImpl.createPatient(PatientResourceImpl.java:44)
	at org.motechproject.openmrs.service.impl.OpenMRSPatientServiceImpl.createPatient(OpenMRSPatientServiceImpl.java:86)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.createPatientTestData(MRSTasksIntegrationBundleIT.java:376)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.setUp(MRSTasksIntegrationBundleIT.java:156)

testCreateEncounterPostActionParameter(org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT)  Time elapsed: 120.316 sec  <<< ERROR!
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:495)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:446)
	at org.motechproject.openmrs.resource.impl.BaseResource.exchange(BaseResource.java:103)
	at org.motechproject.openmrs.resource.impl.BaseResource.postForJson(BaseResource.java:62)
	at org.motechproject.openmrs.resource.impl.PatientResourceImpl.createPatient(PatientResourceImpl.java:44)
	at org.motechproject.openmrs.service.impl.OpenMRSPatientServiceImpl.createPatient(OpenMRSPatientServiceImpl.java:86)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.createPatientTestData(MRSTasksIntegrationBundleIT.java:376)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.setUp(MRSTasksIntegrationBundleIT.java:156)

testCreatePatientPostActionParameter(org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT)  Time elapsed: 120.322 sec  <<< ERROR!
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:495)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:446)
	at org.motechproject.openmrs.resource.impl.BaseResource.exchange(BaseResource.java:103)
	at org.motechproject.openmrs.resource.impl.BaseResource.postForJson(BaseResource.java:62)
	at org.motechproject.openmrs.resource.impl.PatientResourceImpl.createPatient(PatientResourceImpl.java:44)
	at org.motechproject.openmrs.service.impl.OpenMRSPatientServiceImpl.createPatient(OpenMRSPatientServiceImpl.java:86)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.createPatientTestData(MRSTasksIntegrationBundleIT.java:376)
	at org.motechproject.openmrs.it.MRSTasksIntegrationBundleIT.setUp(MRSTasksIntegrationBundleIT.java:156)

shouldCreateEncounter(org.motechproject.openmrs.it.MRSEncounterServiceIT)  Time elapsed: 0.836 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterType(MRSEncounterServiceIT.java:349)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterOne(MRSEncounterServiceIT.java:247)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.setUp(MRSEncounterServiceIT.java:117)

shouldGetLatestEncounter(org.motechproject.openmrs.it.MRSEncounterServiceIT)  Time elapsed: 0.75 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterType(MRSEncounterServiceIT.java:349)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterOne(MRSEncounterServiceIT.java:247)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.setUp(MRSEncounterServiceIT.java:117)

shouldDeleteEncounter(org.motechproject.openmrs.it.MRSEncounterServiceIT)  Time elapsed: 0.788 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterType(MRSEncounterServiceIT.java:349)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.prepareEncounterOne(MRSEncounterServiceIT.java:247)
	at org.motechproject.openmrs.it.MRSEncounterServiceIT.setUp(MRSEncounterServiceIT.java:117)


Results :

Tests in error: 
  MRSTasksIntegrationBundleIT.setUp:157->createEncounterTestData:381->prepareEncounterType:549 NullPointer
  MRSTasksIntegrationBundleIT.setUp:156->createPatientTestData:376 » HttpClientError
  MRSTasksIntegrationBundleIT.setUp:156->createPatientTestData:376 » HttpClientError
  MRSTasksIntegrationBundleIT.setUp:156->createPatientTestData:376 » HttpClientError
  MRSTasksIntegrationBundleIT.setUp:156->createPatientTestData:376 » HttpClientError
  MRSEncounterServiceIT.setUp:1 [...]

2016-11-30 08:55 UTC, shanmukhm commented
sorry forgot to update the code yesterday, after this I'm getting '400 Bad request' in ITs (as in master branch)

2016-11-30 09:44 UTC, kmadej commented
@shanmukhm i am bit confused with your changes now. I think that the best solution will be using two constructors, one with uuid and one with name. And in this test when the encounterType is creating via REST please use constructor with name.

2016-11-30 11:51 UTC, shanmukhm commented
@kmadej we can not add two constructors in EncounterType since both uuid and name are of string.
We can create a new EncounterType only with name and description (according to OpenMRS REST API). UUID is returned after EncounterType is created in openmrs app. So, uuid exists only for already existing encounter type. I think we should not construct with uuid. According to the ticket, when an action of 'create encounter' is selected, user should enter the uuid of existing encounter type.
That's why I only used uuid for task related code. Correct me if I'm wrong.

2016-11-30 13:12 UTC, kmadej commented
Hmm, so maybe the best solution will be to create one constructor :
EncounterType(String uuid, String name, String description)

in task action use EncounterType(uuid, null, null) and EncounterTypeSerializer will use only uuid to create encounter

in test while creating encounterType via REST use EncounterType(null, name, description). Json will use only name and description and will ignore null

2016-11-30 13:39 UTC, shanmukhm commented
Yeah, that sounds good, will make changes accordingly.

2016-12-02 11:54 UTC, kmadej requested changes

2016-12-02 11:54 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceImpl.java
> +        EncounterType type = new EncounterType(encounterType, null);
it should be new EncounterType(null, encounterType). Uuid is a second parameter in constructor

2016-12-02 17:49 UTC, kmadej approved these changes

2016-12-02 17:49 UTC, merged