MOTECH-3080: Fixed observations group
motech/modules pull request #511
Opened 2016-12-27 13:28 UTC by mkruszynski

2016-12-28 12:10 UTC, kmadej requested changes

2016-12-28 12:10 UTC, kmadej commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        parentObservation.setGroupMembers(Arrays.asList(child1, child2, child3, child4));
why 4 children not 3 ?

2016-12-28 16:03 UTC, mkruszynski commented on openmrs/src/test/java/org/motechproject/openmrs/tasks/impl/OpenMRSActionProxyServiceTest.java
> +        parentObservation.setGroupMembers(Arrays.asList(child1, child2, child3, child4));
@kmadej OpenMRS, for some reason, is ignoring nested groupMembers. When I'm creating only the observations which are containing some value (last UUID in group), they're created.

2016-12-29 15:42 UTC, kmadej requested changes

2016-12-29 15:42 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +            if (createdObservation.getGroupMembers() == null) {
this is redundant, it is already handled in getter

2016-12-29 15:42 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +            if (observation.getGroupMembers() != null) {
redundant

2016-12-29 15:42 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +        List<Observation> observationList = encounter.getObs();
please add a comment to this code

2016-12-29 15:42 UTC, kmadej commented on openmrs/src/main/java/org/motechproject/openmrs/service/impl/OpenMRSEncounterServiceImpl.java
> +        for (Observation observation : observationList) {
observationList can be null, please handle this in getObs() getter in Encounter

2016-12-30 13:56 UTC, kkedys commented
@mkruszynski, I checked. The subgroups are not visible in OpenMRS. I verify it in API documentation. 

I created the observations concerning the following schema:

1. Observation with ANC Concept, without obs value and with the following children (obs groupsMembers)
a) Observation with Visit Month Concept, obs value = 3
b) Observation with ANC Visit Concept, obs value = 2nd
c) Observation with Diagnosis Concept, without obs value, with the following children (obs groupsMembers)
          Observation with High Risk Concept, obs value = No

The problem that I reached is the last observation (Observation with High Risk Concept, obs value = No) is not visible on OpenMRS.

2017-01-02 11:02 UTC, mkruszynski commented
@kkedys I checked this for this concepts (every concept had Datatype - Text) and all observations was created successfully. Can you check this one more time?

2017-01-02 12:48 UTC, kkedys commented
@kmadej , I checked one more time and any observations are visible in the OpenMRS.

2017-01-03 15:05 UTC, kmadej commented
OpenMRS ITs fail. Additionally please add person to observation in EncounterService not in ActionProxyService

2017-01-04 13:18 UTC, kmadej approved these changes

2017-01-04 13:18 UTC, merged