MOTECH-3049: Fixed: NPE during a 'sync'.
motech/modules pull request #512
Opened 2016-12-28 13:13 UTC by pkornowski

2016-12-28 13:14 UTC, kmadej requested changes

2016-12-28 13:14 UTC, kmadej commented on dhis2/src/main/java/org/motechproject/dhis2/service/impl/SyncServiceImpl.java
> +            if (dataSetDto.getDataElements() == null) {
do this in createFromDetails method and adjust unit test in DataSetServiceTest

2016-12-30 13:40 UTC, kkedys commented
@kmadej, the pull request is checked.

2016-12-30 13:45 UTC, kmadej approved these changes

2016-12-30 13:45 UTC, merged