MOTECH-3077 CommCare Case Update - Owner Id should not be required
motech/modules pull request #513
Opened 2016-12-29 13:39 UTC by srujan92

Removed the 'owner id' parameter from update case related methods.

2016-12-29 13:39 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-12-29 13:39 UTC, motech-gerrit commented
Can one of the admins verify this patch?

2016-12-29 14:05 UTC, kmadej requested changes

2016-12-29 14:05 UTC, kmadej commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/CaseActionBuilder.java
> -                    .setRequired(true)
why did you remove ownerId ? It should be still available, however not required. So try to set required to false

2016-12-29 20:08 UTC, srujan92 reviewed
@kmadej please see the update changes and see if this is what the required solution for this issue.

2016-12-29 20:08 UTC, srujan92 commented on commcare/src/main/java/org/motechproject/commcare/tasks/builder/CaseActionBuilder.java
> -                    .setRequired(true)
Since we are not using owner id in update case, I thought parameter is not needed. Ok, I will revert the changes and set required to false.

2016-12-30 12:14 UTC, kmadej commented
@srujan92 it seems ok, please fix tests

2017-01-03 13:15 UTC, kmadej commented
@srujan92 please change line 531 in CommcareTasksIntegrationBundleIT. Now it should be '.setRequired(false)'

2017-01-03 17:26 UTC, kmadej approved these changes

2017-01-03 17:26 UTC, merged

2017-01-03 17:27 UTC, srujan92 commented
@kmadej looks like the building gods have granted us successful build :-) , please merge the code when its feasible to you.

2017-01-03 18:04 UTC, kmadej commented
@srujan92 well said :) I've merged the code